#!/usr/bin/env bash
# From-scratch Stage A plus scheduled E2 counterfactual joint training.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export CHECKPOINT_PATH="${CHECKPOINT_PATH:-}"
export POSTTRAJ_STAGE2_ENABLED=false
export POSTTRAJ_JOINT_ENABLED=true
export POSTTRAJ_JOINT_WARMUP_EPOCHS="${POSTTRAJ_JOINT_WARMUP_EPOCHS:-5}"
export POSTTRAJ_JOINT_RAMP_EPOCHS="${POSTTRAJ_JOINT_RAMP_EPOCHS:-5}"
export POSTTRAJ_JOINT_ANCHOR_LOSS_WEIGHT="${POSTTRAJ_JOINT_ANCHOR_LOSS_WEIGHT:-0.25}"
export POSTTRAJ_FUTURE_LOSS_WEIGHT="${POSTTRAJ_FUTURE_LOSS_WEIGHT:-0.1}"
export POSTTRAJ_STAGE2_NUM_LOCAL_HARD="${POSTTRAJ_STAGE2_NUM_LOCAL_HARD:-64}"
export POSTTRAJ_STAGE2_NUM_BALANCED="${POSTTRAJ_STAGE2_NUM_BALANCED:-64}"
export MAX_EPOCHS="${MAX_EPOCHS:-30}"
export LR="${LR:-1e-4}"
export CHECKPOINT_SAVE_TOP_K="${CHECKPOINT_SAVE_TOP_K:-3}"
export CHECKPOINT_SAVE_LAST="${CHECKPOINT_SAVE_LAST:-true}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-PB_G_PostTrajFuture_Joint30}"

exec bash "${SCRIPT_DIR}/run_posttraj_future_stageA.sh"
